const data =  {
    menus: [
        {
            _id:'1',
            name: 'Spicy Noodles',
            category: 'veg',
            image:'/images/img6.jpg',
            price: 60,
            Available:10,
            type: 'veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'2',
            name: 'Spicy Noodles',
            category: 'veg',
            image: '/images/img6.jpg',
            price: 60,Available:10,
            type: 'veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'3',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,Available:10,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'4',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,Available:10,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'5',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: ' /images/img6.jpg',
            price: 60,Available:10,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'6',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'7',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'8',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'9',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'10',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
        {
            _id:'11',
            name: 'Spicy Noodles',
            category: 'non-veg',
            image: '/images/img6.jpg',
            price: 60,
            type: 'non-veg',
            rating: 4.5,
            numReviews: 10,
            description:"high quality menu",
        },
    ]
}
export default data;